variable "pub_sub_1a_id" {}
variable "pub_sub_2b_id" {}
variable "pri_sub_3a_id" {}
variable "pri_sub_4b_id" {}
variable "pri_sub_5a_id" {}
variable "pri_sub_6b_id" {}
variable "web_security_group_id" {}
variable "app_security_group_id" {}
variable "db_security_group_id" {}
variable "key_name" {}